[package]
name = "parcelona"
version = "0.1.5"
authors = ["Cergoo"]
edition = "2021"
description = "minimalistic elegance parser combinator library"
license = "MIT"
repository = "https://github.com/Cergoo/parcelona"
categories = ["parsing"]
documentation = "https://docs.rs/parcelona"
readme = "README.md"

[dependencies]
byteorder = "1.5.0"

[dev-dependencies]
atoi = "2.0.0"
byteorder = "1.5.0"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

