[package]
name = "parselona"
version = "0.1.0"
authors = ["prof"]
edition = "2021"

[dev-dependencies]
atoi = "2.0.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

