[package]
name = "parcelona"
version = "0.1.0"
authors = ["Cergoo"]
edition = "2021"
description = "minimalistic elegance parser combinator library"
license = "GNU General Public License v3.0"
repository = "https://github.com/Cergoo/parcelona"
categories = ["parsing"]

[dev-dependencies]
atoi = "2.0.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

